global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: grzegorzjaksik1@gmail.com
    from: grzegorzjaksik1@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: grzegorzjaksik1@gmail.com
    auth_identity: grzegorzjaksik1@gmail.com
    auth_password: ixfmxdxfseofgzyd
    send_resolved: true