global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: myemail@gmail.com
    from: myemail@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: myemail@gmail.com
    auth_identity: myemail@gmail.com
    auth_password: **
    send_resolved: true
