
#file contains cronjob list pods from Namespace using service account bind to role with specific rules.
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: list-pods
  namespace: baza
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: list-user
          containers:
          - name: list-pods
            image: bitnami/kubectl
            #imagePullPolicyservice account : IfNotPresent
            command:
            - /bin/sh
            - -c
            - "kubectl get pods"
          restartPolicy: Never
---          
apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-user
  namespace: baza
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: baza
  name: list-pods
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: list-pods
  namespace: baza
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: list-user # "name" is case sensitive
  namespace: baza
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: list-pods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
