apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    kurs: dor6
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kurs: dor6
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        command: [bash]
        args: ["-c","sleep 20"]
      - name: nginx2
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        command: [bash]
        args: ["-c","sleep 10"]
    